{% set name = "ddsketch" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddsketch-{{ version }}.tar.gz
  sha256: aa8f20b2965e61731ca4fee2ca9c209f397f5bbb23f9d192ec8bd7a2f5bd9824

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >3.6
    - setuptools-scm
  run:
    - protobuf >=3.0.0
    - python >3.6
    - six

test:
  imports:
    - ddsketch
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/datadog/sketches-py
  summary: Distributed quantile sketches
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aymondebroglie
